const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:1280,height:900}}),requests=[],records=new Map(),errors=[],outcomes=[];let checks=0;
p.on('pageerror',e=>errors.push(e.message));p.on('response',async r=>{if(r.url().startsWith('https://oss.exercisedb.dev/api/')){requests.push(r.status());if(r.ok())try{for(const e of (await r.json()).data||[])records.set(e.exerciseId,e);}catch{}}});
try{await p.goto(process.env.GYMBUDDY_URL||'http://127.0.0.1:8879');await p.locator('#workout-age').fill('30');await p.locator('#experience').selectOption('advanced');await p.locator('#limitations-dropdown').evaluate(e=>e.open=true);
async function setLimits(limits){for(const x of ['low-impact','knee','back','shoulder','wrist','balance','other'])await p.locator('[name="limitation"][value="'+x+'"]').setChecked(limits.includes(x));}
async function generate(label,required=false){await p.locator('#generate-workout').click();await p.waitForFunction(()=>!document.querySelector('#generate-workout').disabled,{},{timeout:150000});const status=await p.locator('#builder-status').innerText();outcomes.push({label,status});if(required)assert(status.includes('is ready'),status);else assert(status.includes('is ready')||status.includes('restrictions have not been relaxed')||status.includes('unlisted limitation'),status);checks++;return status;}
await setLimits(['knee']);await generate('original knee quick',true);
let replaced=false;const before=await p.locator('.exercise-card').evaluateAll(es=>es.map(e=>e.dataset.exerciseId));for(let i=0;i<before.length;i++){const c=p.locator('.exercise-card').nth(i);await c.getByRole('button',{name:'Replace exercise',exact:true}).click();if(await c.locator('.alternatives button').count()>1){await c.locator('.alternatives button').first().click();const after=await p.locator('.exercise-card').evaluateAll(es=>es.map(e=>e.dataset.exerciseId));assert(after.filter((id,j)=>id!==before[j]).length===1);checks++;replaced=true;break;}}
await p.locator('#plan-mode').selectOption('weekly');await generate('knee weekly',true);assert(await p.locator('.day-card').count()===7);checks++;
await p.locator('#plan-mode').selectOption('quick');
for(const limits of [['low-impact'],['back'],['shoulder'],['wrist'],['balance'],['other'],['knee','low-impact'],['knee','balance'],['back','knee'],['shoulder','wrist'],['knee','wrist','balance']]){await setLimits(limits);await generate(limits.join('+'));}
for(const duration of ['45','60']){await setLimits(['knee']);await p.locator('#duration').selectOption(duration);await generate('knee '+duration,true);}
for(const stretching of ['partner','both']){await p.locator('#stretching-preference').selectOption(stretching);await generate('knee '+stretching,true);}
assert(errors.length===0);checks++;console.log(JSON.stringify({checks,replaced,requests,records:records.size,outcomes,runtimeErrors:errors},null,2));fs.writeFileSync(path.join(process.env.TEMP,'gymbuddy-limitations-live.json'),JSON.stringify({checks,replaced,requests,records:records.size,outcomes,runtimeErrors:errors},null,2));fs.writeFileSync(path.join(process.env.TEMP,'gymbuddy-limitations-records.json'),JSON.stringify([...records.values()]));
await p.locator('#workout-results').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(process.env.TEMP,'gymbuddy-limitations-desktop.png')});
}finally{fs.writeFileSync(path.join(process.env.TEMP,'gymbuddy-limitations-live-attempt.json'),JSON.stringify({checks,requests,records:records.size,outcomes,runtimeErrors:errors},null,2));await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
